services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}  # Use the value of NODE_ENV from .env or default to development
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app  # For live-reloading in development
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - postgres
    links:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"  # Expose pgAdmin on port 8080
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - default 

volumes:
  postgres_data:
  pgadmin_data:
